/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.HoaDonController;
import Controller.KhuyenMaiController;
import Model.KhuyenMaiModel;
import Model.UserModel;
import Object.HoaDon;
import Object.KhachHang;
import Object.KhuyenMai;
import Object.User;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import static java.lang.System.exit;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ADMIN
 */
public class HoaDonView extends javax.swing.JPanel {
    private Date ngayLap;
    private String gioVao;
    private String gioRa;
    private String nguoiLap;
    private String danhSachSanPham;
    private String soLuongSanPham;
    private double tongTien;
    private User currentUser;
    private Home home;
    private KhachHang khachHangDangChon;

    /**
     * Creates new form HoaDon
     */
//    public HoaDonView(User currentUser) {
//        this.currentUser = currentUser;
//        initComponents();
//        lblKhuyenMai.setText("0%");
//    }
//    public HoaDonView() {
//        initComponents();
//        lblKhuyenMai.setText("0%");
//    }
    public HoaDonView(User currentUser, Home home) {
        this.currentUser = currentUser;
        this.home = home;
        initComponents();
        lblKhuyenMai.setText("0%");
    }

    public void setInvoiceData(Date ngayLap, String gioVao, String gioRa,
                               String danhSachSanPham, String soLuongSanPham, double tongTien) {
        this.ngayLap = ngayLap;
        this.gioVao = gioVao;
        this.gioRa = gioRa;
        this.nguoiLap = String.valueOf(currentUser.getMaNV()); // dùng mã nhân viên

        this.danhSachSanPham = danhSachSanPham;
        this.soLuongSanPham = soLuongSanPham;
        this.tongTien = tongTien;

        DecimalFormat df = new DecimalFormat("#,###");
        lblTongTien1.setText(df.format(tongTien));
        lblTongTien3.setText(df.format(tongTien));

        try {
            UserModel userModel = new UserModel();
            String tenNguoiLap = userModel.getFullNameByMaNV(currentUser.getMaNV());
            lblNguoiLap.setText(tenNguoiLap); // hiển thị họ tên
        } catch (Exception e) {
            lblNguoiLap.setText("Không xác định");
            e.printStackTrace();
        }
    }





        // ✅ Constructor mới có tham số để truyền thông tin hóa đơn
    public HoaDonView(Date ngayLap, String gioVao, String gioRa, int soLuong, double tongTien, double khuyenMai, double tongTienThuc) {
        initComponents();

        // Format ngày và giờ
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String ngay = sdf.format(ngayLap);

        lblNgayThang.setText(ngay);
        lblGio.setText(gioRa); // hoặc hiển thị "gioVao - gioRa"
        lblSoLuong.setText(String.valueOf(soLuong));
        lblTongTien.setText(String.format("%.0f VNĐ", tongTienThuc));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        lblTongTien2 = new javax.swing.JLabel();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblNgayThang = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnKhuyenMai = new javax.swing.JButton();
        lblKhuyenMai = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblNguoiLap = new javax.swing.JLabel();
        lblTongTien1 = new javax.swing.JLabel();
        lblTongTien3 = new javax.swing.JLabel();
        btnMangVe = new javax.swing.JRadioButton();
        btnOLai = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        btnKhachHang = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("iagfiuabuiofawuofewo");

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        lblTongTien2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien2.setText("Tổng tiền");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Khách hàng");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tổng tiền hàng :");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien.setText("Tổng tiền");

        lblNgayThang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgayThang.setText("Ngày tháng");

        lblGio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGio.setText("Giờ");

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoLuong.setText("Số lượng");
        lblSoLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.NW_RESIZE_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Giảm giá");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("HÓA ĐƠN");

        btnKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKhuyenMai.setText("...");
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });

        lblKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKhuyenMai.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Khách cần trả");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Khách thanh toán");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Loại đơn");

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhân viên :");

        lblNguoiLap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNguoiLap.setText("người lập");

        lblTongTien1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien1.setText("Tổng tiền");

        lblTongTien3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongTien3.setText("Tổng tiền");

        btnMangVe.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnMangVe);
        btnMangVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMangVe.setText("Mang về");
        btnMangVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMangVeActionPerformed(evt);
            }
        });

        btnOLai.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnOLai);
        btnOLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOLai.setText("Dùng tại quán");
        btnOLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOLaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Khách hàng");

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhachHang.setText("Khách hàng");

        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKhachHang.setText("...");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTongTien1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTongTien3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOLai)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(lblNgayThang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoLuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayThang)
                    .addComponent(lblGio)
                    .addComponent(jLabel4)
                    .addComponent(lblNguoiLap))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblKhachHang)
                    .addComponent(btnKhachHang))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblKhuyenMai)
                    .addComponent(btnKhuyenMai))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTongTien3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTongTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnThanhToan)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private KhuyenMaiModel khuyenMaiModel = new KhuyenMaiModel();
    private KhuyenMai khuyenMaiDangChon;
    
    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
       double tongTien = this.tongTien; // lấy từ hóa đơn

        int soLuong = 0;
        try {
            String[] parts = soLuongSanPham.split(",");
            for (String p : parts) {
                soLuong += Integer.parseInt(p.trim());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng số lượng sản phẩm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (khachHangDangChon == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khách hàng trước khi áp dụng khuyến mãi!");
            return;
        }

        List<KhuyenMai> danhSachApDung = khuyenMaiModel.getKhuyenMaiApDung(khachHangDangChon, tongTien, soLuong);

        JDialog dialog = new JDialog(SwingUtilities.getWindowAncestor((Component) evt.getSource()), "Chọn khuyến mãi", Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setSize(850, 400);
        dialog.setResizable(true);
        dialog.setLocationRelativeTo(null);

        KhuyenMaiFrame.KhuyenMaiSelectionListener listener = new KhuyenMaiFrame.KhuyenMaiSelectionListener() {
            public void onKhuyenMaiSelected(KhuyenMai km) {
                lblKhuyenMai.setText(km.getPhanTramGiam());
                khuyenMaiDangChon = km;
                capNhatTongTienThuc();
                dialog.dispose();
            }
        };

        KhuyenMaiFrame kmPanel = new KhuyenMaiFrame(danhSachApDung, listener);
        dialog.setContentPane(kmPanel.getContentPane());
        dialog.setVisible(true);

    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void capNhatTongTienThuc() {
        double phanTram = 0;

        try {
            String text = lblKhuyenMai.getText().replaceAll("[^\\d.]", ""); // loại bỏ ký tự %, VNĐ
            if (!text.isEmpty()) {
                phanTram = Double.parseDouble(text);
            }
        } catch (NumberFormatException e) {
            phanTram = 0;
        }

        double tienThucTra = tongTien - (tongTien * phanTram / 100);

        DecimalFormat df = new DecimalFormat("#,###");
        lblTongTien1.setText(df.format(tienThucTra));
        lblTongTien3.setText(df.format(tienThucTra));
    }
    
    private void btnMangVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMangVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMangVeActionPerformed

    private void btnOLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOLaiActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        double khuyenMai = 0;

        if (khuyenMaiDangChon != null) {
            try {
                String giamText = khuyenMaiDangChon.getPhanTramGiam().replaceAll("[^\\d.]", "");
                khuyenMai = Double.parseDouble(giamText);
            } catch (NumberFormatException ex) {
                khuyenMai = 0;
            }
        }

        double tongTienThuc = tongTien - (tongTien * khuyenMai / 100);

        // ✅ Kiểm tra loại đơn
        String loaiDon = "";
        if (btnMangVe.isSelected()) {
            loaiDon = "Mang về";
        } else if (btnOLai.isSelected()) {
            loaiDon = "Dùng tại quán";
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn loại đơn (mang về hoặc dùng tại quán)!");
            return;
        }

        // ✅ Kiểm tra khách hàng đã chọn chưa
        if (khachHangDangChon == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hoặc thêm khách hàng!");
            return;
        }

        HoaDon hoaDon = new HoaDon(
            0,                         // maHoaDon
            ngayLap,
            gioVao,
            gioRa,
            nguoiLap,
            danhSachSanPham,
            soLuongSanPham,
            tongTien,
            khuyenMai,
            tongTienThuc,
            loaiDon,
            khachHangDangChon.getMaKH()  // ✅ truyền mã khách hàng
        );

        HoaDonController controller = new HoaDonController();
        boolean result = controller.themHoaDon(hoaDon);

        if (result) {
            JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
            home.clearInvoiceItems();
            SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi khi lưu hóa đơn.");
        }

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
            Window parent = SwingUtilities.getWindowAncestor(this);
            ThemKhachHangFrame dialog = new ThemKhachHangFrame(SwingUtilities.getWindowAncestor(this), khachHang -> {
                    this.khachHangDangChon = khachHang;
                    lblKhachHang.setText(khachHang.getHoTen());
                }
            );
            dialog.setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JRadioButton btnMangVe;
    private javax.swing.JRadioButton btnOLai;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblNgayThang;
    private javax.swing.JLabel lblNguoiLap;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTongTien1;
    private javax.swing.JLabel lblTongTien2;
    private javax.swing.JLabel lblTongTien3;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblGio() {
        return lblGio;
    }

    public JLabel getLblNgayThang() {
        return lblNgayThang;
    }

    public JLabel getLblSoLuong() {
        return lblSoLuong;
    }

    public JLabel getLblTongTien() {
        return lblTongTien;
    }

    public void setLblGio(JLabel lblGio) {
        this.lblGio = lblGio;
    }

    public void setLblNgayThang(JLabel lblNgayThang) {
        this.lblNgayThang = lblNgayThang;
    }

    public void setLblSoLuong(JLabel lblSoLuong) {
        this.lblSoLuong = lblSoLuong;
    }

    public void setLblTongTien(JLabel lblTongTien) {
        this.lblTongTien = lblTongTien;
    }

    public JLabel getLblGiamGia() {
        return lblKhuyenMai;
    }

    public void setLblGiamGia(JLabel lblGiamGia) {
        this.lblKhuyenMai = lblGiamGia;
    }

    public JLabel getLblNguoiLap() {
        return lblNguoiLap;
    }

    public void setLblNguoiLap(JLabel lblNguoiLap) {
        this.lblNguoiLap = lblNguoiLap;
    }

    
}
